name: ecommerce_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: "^0.16.0"
  firebase_core: "0.7.0"
  firebase_auth: "^0.20.0+1"
  json_annotation: ^3.1.1
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  google_fonts: ^1.1.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
